# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options


variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TRAIN_LOG_DIR: "/home/gitlab-runner/work_dirs/$CI_PROJECT_NAME/$CI_JOB_ID-$CI_JOB_NAME"
  SUBMISSION: "submission_${CI_JOB_ID}.csv"
  EXPERIMENT_NAME: "${CI_PROJECT_NAME}"
  CONDA_PATH: /home/gitlab-runner/miniconda3
  FORCE_CUDA: 1
  MMCV_WITH_OPS: 1

.conda_setup: &conda_setup
  before_script:
    # get system hardware/software information
    - lshw -short -c memory -c processor -c network -c storage -c volume -c disk
    - uname -a
    - df -h -x squashfs -x tmpfs -x devtmpfs
    - du -sh ..

    - nvidia-smi
    - export N_GPUS=$(nvidia-smi -L | wc -l)
    - source ~/.bashrc

    # setup conda env
    - export PATH="${CONDA_PATH}/bin:$PATH"
    - export MPLBACKEND=AGG
    - export TORCH_HOME=/home/gitlab-runner/.cache/torch
    # - conda update -n base -c defaults conda
    # - rm -rf ${CONDA_PATH}/envs/$CI_PROJECT_NAME
    # - conda env update --prefix ${CONDA_PATH}/envs/$CI_PROJECT_NAME
    - source activate ${CONDA_PATH}/envs/$CI_PROJECT_NAME

.train_job_common: &train_job_common
  <<: *conda_setup
  stage: train
  coverage: '/Metric Score = \d+\.\d+/'
  timeout: 1w
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - train_log
      - test_results
      - $SUBMISSION
      - $SUBMISSION.zip
      - $SUBMISSION.7z
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $CI_JOB_NAME

.test_job_common: &test_job_common
  <<: *conda_setup
  stage: test
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $CI_JOB_NAME
  timeout: 1d
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - test_results
      - $SUBMISSION
      - $SUBMISSION.zip
      - $SUBMISSION.7z


before_script:
  # get system hardware/software information
  - lshw -short -c memory -c processor -c network -c storage -c volume -c disk
  - uname -a
  - df -h -x squashfs -x tmpfs -x devtmpfs
  - du -sh ..

after_script:
  - pwd
  - echo $TRAIN_LOG_DIR
#  - cp -r $TRAIN_LOG_DIR train_log
#  - 7z a $SUBMISSION.7z $SUBMISSION -sdel

stages:
  - train
  - test



##########################################
lidar_camx1.5_st_ch:
  <<: *train_job_common
  tags:
    - dai-gpu9-2
  script:
    - cd mmdetection3d
    - ln -s /home/gitlab-runner/data data
    - pip install -e .
    - python projects/BEVFusion/setup.py develop
    - export PYTHONPATH=$PWD:$PYTHONPATH
    - python tools/train.py projects/BEVFusion/configs/bevfusion_lidar-cam_st_ch.py --amp
      --work-dir $TRAIN_LOG_DIR
      --cfg-options load_from=https://download.openmmlab.com/mmdetection3d/v1.1.0_models/bevfusion/bevfusion_lidar-cam_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d-5239b1af.pth

      
##########################################
lidar_camx2_st_glss:
  <<: *train_job_common
  tags:
    - daigpu9-3
  script:
    - cd mmdetection3d
    - ln -s /home/demo/ravuri/data data
    - pip install -e .
    - python projects/BEVFusion/setup.py develop
    - export PYTHONPATH=$PWD:$PYTHONPATH
    - python tools/train.py projects/BEVFusion/configs/bevfusion_lidar-cam_swin_tiny.py --amp
      --work-dir $TRAIN_LOG_DIR 
      --cfg-options load_from=https://download.openmmlab.com/mmdetection3d/v1.1.0_models/bevfusion/bevfusion_lidar-cam_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d-5239b1af.pth

